name: drawing_app
description: A new Flutter project for drawing shapes on a canvas.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true